services:
  app:
    build: .
    container_name: book
    command: /bin/bash entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - ./books:/books/books
      - book-migrations:/books/books/api/migrations
      - book-static:/books/static
      - book-media:/books/media
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_DB=${DJANGO_DB_NAME}
      - POSTGRES_USER=${DJANGO_DB_USER}
      - POSTGRES_PASSWORD=${DJANGO_DB_PASSWORD}
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - ./.env

volumes:
  pg-data:
  book-migrations:
  book-static:
  book-media: